apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-ram-monitor
  labels: 
    app: cpu-ram-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-ram-monitor
  template:
    metadata:
      labels:
        app: cpu-ram-monitor
    spec:
      containers:
      - name: cpu-ram-monitor
        image: cpu_ram_monitor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi