apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: system-metrics-alerts
  namespace: monitoring
  labels:
    release: promegralert-stack  # Make sure this name matches your Prometheus instance
spec:
  groups:
    - name: system-metrics.rules
      rules:
        - alert: alert from FLASK-APPLICATION:WARNING(***HighCPUUsage-ALERT-TRIGGERED***)
          expr: cpu_usage_percent > 4
          for: 1m
          labels:
            severity: warning
            namespace: monitoring
          annotations:
            summary: "High CPU usage detected"
            description: "CPU usage is above 04% for more than 1 minute."

        - alert: alert from FLASK-APPLICATION:PRECAUTION(***HighMemoryUsage-ALERT-TRIGGERED***)
          expr: memory_usage_percent > 30
          for: 1m
          labels:
            severity: critical
            namespace: monitoring
          annotations:
            summary: "High memory usage detected"
            description: "Memory usage is above 30% for more than 1 minutes."

        - alert: alert from FLASK-APPLICATION:PRECAUTION***(NetworkTrafficSpike***)
          expr: increase(network_bytes_sent_total[1m]) > 100000
          for: 1m
          labels:
            severity: warning
            namespace: monitoring
          annotations:
            summary: "Network traffic spike detected"
            description: "More than 10MB of data sent in the last minute on one interface."
